idf_component_register(SRCS "tmf8829_firmware.c" 
                            "main.c"
                            "tmf8829.c"
                            "tmf8829_shim.cpp"
                            "tmf8829_app.cpp"
                            "tmf8829_help.cpp"
                       INCLUDE_DIRS ".")
